# Site settings
title: Studio Dentistico dott. Stefania Rinaldi - Fontaniva Padova
description: "Dentista a Fontaniva. La Dott. Stefania Rinaldi riceve nel suo ambulatorio di Fontaniva dal 1995."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero:
    hero_img: hero.jpg
    hero_title: Dentista a Fontaniva
    hero_description: Il sorriso sulla bocca della tua famiglia

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 049 594 21 80
    email: dentista@fontaniva.net
    address: Piazzetta Arma di Cavalleria, 4 <br> Fontaniva (Padova)

# Opening hours
monday_friday: 9:30 – 18:00
saturday: Chiuso
sunday: Chiuso

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Piazzetta Arma di Cavalleria 4, Fontaniva, Padova
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2020 Stefania Rinaldi - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:
